import React, { Component, useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import { Activity, AlertTriangle, BarChart3, Bell, ChevronRight, Database, FileText, Gauge, Layers3, Map as MapIcon, Menu, Moon, Search, Settings as SettingsIcon, ShieldCheck, Sun, Thermometer, Users, X, ArrowUpRight, CheckCircle2, Info, Download, Filter, SlidersHorizontal } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, BarChart, Bar } from 'recharts';
import './styles.css';

const RISK = {
  W06: { wbgt: 35.776, utci: 42.6, vuln: 0.595, excess: 0.307, low: 0.177, high: 0.448, tier: 'Orange' },
  W08: { wbgt: 35.971, utci: 43.0, vuln: 0.652, excess: 0.300, low: 0.172, high: 0.440, tier: 'Orange' },
  W02: { wbgt: 35.752, utci: 42.6, vuln: 0.587, excess: 0.283, low: 0.163, high: 0.412, tier: 'Orange' },
  W05: { wbgt: 35.971, utci: 43.0, vuln: 0.560, excess: 0.209, low: 0.120, high: 0.305, tier: 'Orange' },
  W03: { wbgt: 35.786, utci: 42.6, vuln: 0.272, excess: 0.177, low: 0.103, high: 0.255, tier: 'Orange' },
  W09: { wbgt: 35.786, utci: 42.6, vuln: 0.710, excess: 0.167, low: 0.096, high: 0.245, tier: 'Orange' },
  W04: { wbgt: 35.752, utci: 42.6, vuln: 0.331, excess: 0.152, low: 0.088, high: 0.219, tier: 'Orange' },
  W07: { wbgt: 35.752, utci: 42.6, vuln: 0.742, excess: 0.139, low: 0.079, high: 0.203, tier: 'Orange' },
  W10: { wbgt: 35.776, utci: 42.6, vuln: 0.542, excess: 0.117, low: 0.068, high: 0.170, tier: 'Orange' },
  W01: { wbgt: 35.786, utci: 42.6, vuln: 0.463, excess: 0.106, low: 0.062, high: 0.154, tier: 'Orange' }
};

const trend = [
  { day: '12 Jun', wbgt: 31.8, utci: 37.2 }, { day: '13 Jun', wbgt: 32.6, utci: 38.0 },
  { day: '14 Jun', wbgt: 33.1, utci: 39.1 }, { day: '15 Jun', wbgt: 34.0, utci: 40.0 },
  { day: '16 Jun', wbgt: 35.1, utci: 41.4 }, { day: '17 Jun', wbgt: 35.8, utci: 42.6 }
];

const nav = [
  ['Dashboard', Gauge], ['Risk Map', MapIcon], ['Analytics', BarChart3], ['Alerts', Bell], ['Reports', FileText], ['Data Layers', Layers3]
];

const pageMeta = {
  Dashboard: ['CITY HEAT MONITORING', 'Heat Risk Overview', 'Operational view of current thermal stress and the T+4 forecast.'],
  'Risk Map': ['SPATIAL INTELLIGENCE', 'Risk Map', 'Explore ward-level thermal stress across Kolkata.'],
  Analytics: ['MODEL ANALYTICS', 'Analytics', 'Inspect thermal trends, vulnerability and forecast behaviour.'],
  Alerts: ['RESPONSE CENTER', 'Alerts', 'Priority conditions requiring attention.'],
  Reports: ['EVIDENCE & OUTPUTS', 'Reports', 'Review model outputs, methodology and exportable summaries.'],
  'Data Layers': ['DATA CONTROL', 'Data Layers', 'Choose which HEATWARD data layer is visualized on the map.'],
  Settings: ['SYSTEM', 'Settings', 'Control interface preferences and model display behaviour.']
};

class AppErrorBoundary extends Component {
  constructor(props){ super(props); this.state={error:null}; }
  static getDerivedStateFromError(error){ return {error}; }
  render(){
    if(this.state.error) return <div className="fatal"><div className="fatal-box"><div className="eyebrow">HEATWARD RUNTIME ERROR</div><h2>The dashboard could not render.</h2><p>Open the browser console and share the red error with me.</p><pre>{String(this.state.error?.stack || this.state.error)}</pre></div></div>;
    return this.props.children;
  }
}

function App(){
  const [dark,setDark]=useState(true); const [active,setActive]=useState('Dashboard'); const [selectedWard,setSelectedWard]=useState('W06'); const [mapMode,setMapMode]=useState('risk'); const [mobileOpen,setMobileOpen]=useState(false);
  const selected=RISK[selectedWard];
  const navigate=(page)=>{setActive(page);setMobileOpen(false)};
  return <div className={dark?'app dark':'app light'}>
    <aside className={mobileOpen?'sidebar open':'sidebar'}>
      <div className="brand-row"><div className="brand-mark">H</div><div><div className="brand">HEATWARD</div><div className="brand-sub">THERMAL INTELLIGENCE</div></div><button className="icon-btn mobile-close" onClick={()=>setMobileOpen(false)}><X size={18}/></button></div>
      <div className="nav-label">MONITOR</div>
      <nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'nav-item active':'nav-item'} onClick={()=>navigate(label)}><Icon size={17}/><span>{label}</span></button>)}</nav>
      <div className="sidebar-bottom"><button className={active==='Settings'?'nav-item active':'nav-item'} onClick={()=>navigate('Settings')}><SettingsIcon size={17}/><span>Settings</span></button><div className="model-chip"><ShieldCheck size={16}/><div><b>MODEL 2</b><span>Leakage check passed</span></div></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setMobileOpen(true)}><Menu size={20}/></button><div className="search"><Search size={16}/><input placeholder="Search wards, reports, data..." /></div><div className="top-actions"><div className="location"><span className="dot"></span>Kolkata</div><button className="theme-btn" onClick={()=>setDark(!dark)} title="Toggle theme">{dark?<Sun size={17}/>:<Moon size={17}/>}</button><div className="avatar">SS</div></div></header>
      <div className="content"><PageHead active={active}/>{active==='Dashboard'&&<Dashboard selectedWard={selectedWard} setSelectedWard={setSelectedWard} selected={selected} mapMode={mapMode} setMapMode={setMapMode} navigate={navigate}/>} {active==='Risk Map'&&<RiskPage selectedWard={selectedWard} setSelectedWard={setSelectedWard} mapMode={mapMode} setMapMode={setMapMode}/>} {active==='Analytics'&&<AnalyticsPage/>} {active==='Alerts'&&<AlertsPage navigate={navigate}/>} {active==='Reports'&&<ReportsPage/>} {active==='Data Layers'&&<LayersPage mapMode={mapMode} setMapMode={setMapMode} navigate={navigate}/>} {active==='Settings'&&<SettingsPage dark={dark} setDark={setDark}/>}</div>
    </main>
  </div>
}

function PageHead({active}){const [eyebrow,title,desc]=pageMeta[active]; return <div className="page-head"><div><div className="eyebrow">{eyebrow} · 17 JUN 2023</div><h1>{title}</h1><p>{desc}</p></div><div className="forecast-badge"><span>FORECAST HORIZON</span><b>T + 4 DAYS</b></div></div>}

function Dashboard({selectedWard,setSelectedWard,selected,mapMode,setMapMode,navigate}){return <>
  <section className="hero-grid"><RiskCard selected={selected}/><Metric title="WBGT" value="35.8°C" sub="Outdoor thermal stress" icon={<Thermometer size={17}/>}/><Metric title="UTCI" value="42.6°C" sub="Physiological stress" icon={<Activity size={17}/>}/><Metric title="VULNERABILITY" value={`${(selected.vuln*100).toFixed(1)}%`} sub={`Selected ward · ${selectedWard}`} icon={<Users size={17}/>}/></section>
  <section className="map-section panel"><MapHeader mapMode={mapMode} setMapMode={setMapMode}/><RiskMap selectedWard={selectedWard} setSelectedWard={setSelectedWard} mapMode={mapMode}/></section>
  <section className="lower-grid"><Upcoming selectedWard={selectedWard} setSelectedWard={setSelectedWard} navigate={navigate}/><Trend/><WardDetail selectedWard={selectedWard} selected={selected}/></section>
  <ModelPanel/>
</>}

function RiskCard({selected}){return <div className="risk-card panel"><div className="card-top"><span className="section-kicker">CURRENT CITY RISK</span><span className="status-dot orange"></span></div><div className="risk-word">ORANGE</div><div className="risk-desc">Elevated thermal stress</div><div className="risk-meta"><span><Thermometer size={14}/> Peak day</span><b>17 Jun 2023</b></div><div className="risk-meta"><span><Activity size={14}/> City excess burden</span><b>1.96 <small>[1.13–2.85]</small></b></div></div>}
function Metric({title,value,sub,icon}){return <div className="metric-card panel"><div className="metric-icon">{icon}</div><span className="section-kicker">{title}</span><strong>{value}</strong><small>{sub}</small></div>}
function MapHeader({mapMode,setMapMode}){return <div className="map-head"><div><span className="section-kicker">SPATIAL RISK</span><h2>Kolkata Ward Distribution</h2></div><div className="map-controls">{[['risk','Risk'],['wbgt','WBGT'],['vulnerability','Vulnerability']].map(([id,label])=><button key={id} className={mapMode===id?'seg active':'seg'} onClick={()=>setMapMode(id)}>{label}</button>)}</div></div>}
function Upcoming({selectedWard,setSelectedWard,navigate}){return <div className="panel upcoming"><div className="panel-head"><div><span className="section-kicker">PRIORITY WARDS</span><h2>Upcoming Risk</h2></div><button className="text-btn" onClick={()=>navigate('Risk Map')}>Open map <ChevronRight size={15}/></button></div><div className="ward-list">{Object.entries(RISK).slice(0,5).map(([id,d])=><button className={selectedWard===id?'ward-row selected':'ward-row'} key={id} onClick={()=>setSelectedWard(id)}><span className="ward-id">{id}</span><span className="ward-risk"><i className="risk-dot"></i>{d.tier}</span><span className="ward-wbgt">{d.wbgt.toFixed(1)}°C</span><ChevronRight size={14}/></button>)}</div></div>}
function Trend(){return <div className="panel trend"><div className="panel-head"><div><span className="section-kicker">THERMAL TREND</span><h2>Recent stress</h2></div><span className="date-pill">12–17 JUN</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="fillGreen" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#39ff14" stopOpacity={0.24}/><stop offset="100%" stopColor="#39ff14" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={0.12}/><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={10}/><YAxis tickLine={false} axisLine={false} fontSize={10} width={30}/><Tooltip contentStyle={{borderRadius:8,border:'1px solid var(--border)',background:'var(--surface)',color:'var(--text)'}}/><Area type="monotone" dataKey="wbgt" stroke="#39ff14" strokeWidth={2.2} fill="url(#fillGreen)"/><Area type="monotone" dataKey="utci" stroke="#8f9a94" strokeWidth={1.5} fill="none"/></AreaChart></ResponsiveContainer></div><div className="legend-line"><span><i className="line green"></i>WBGT</span><span><i className="line gray"></i>UTCI</span></div></div>}
function WardDetail({selectedWard,selected}){return <div className="panel ward-detail"><div className="panel-head"><div><span className="section-kicker">SELECTED WARD</span><h2>{selectedWard}</h2></div><span className="risk-badge">ORANGE</span></div><div className="detail-grid"><Detail label="WBGT" value={`${selected.wbgt.toFixed(1)}°C`}/><Detail label="UTCI" value={`${selected.utci.toFixed(1)}°C`}/><Detail label="Vulnerability" value={`${(selected.vuln*100).toFixed(1)}%`}/><Detail label="Excess burden" value={selected.excess.toFixed(2)}/></div><div className="confidence"><div><span>Estimated excess burden</span><b>{selected.excess.toFixed(2)}</b></div><p>Range {selected.low.toFixed(2)}–{selected.high.toFixed(2)}</p></div></div>}
function Detail({label,value}){return <div className="detail"><span>{label}</span><b>{value}</b></div>}
function ModelPanel(){return <section className="transparency panel"><div><span className="section-kicker">MODEL TRANSPARENCY</span><h2>Forecast integrity</h2><p>Model 2 uses same-day weather and lagged outcomes, with year-based temporal validation and a leakage assertion.</p></div><div className="checks"><Check label="Year-based split"/><Check label="Heat season represented"/><Check label="Leakage check passed"/></div></section>}
function Check({label}){return <div className="check"><CheckCircle2 size={13}/>{label}</div>}

function RiskPage({selectedWard,setSelectedWard,mapMode,setMapMode}){return <><section className="map-section panel full-map"><MapHeader mapMode={mapMode} setMapMode={setMapMode}/><RiskMap selectedWard={selectedWard} setSelectedWard={setSelectedWard} mapMode={mapMode} tall/><div className="map-explainer"><Info size={15}/><span>Only wards with model outputs are colored. Unmodeled wards remain neutral rather than being assigned invented risk values.</span></div></section><div className="two-col"><div className="panel info-panel"><span className="section-kicker">DISTRIBUTION</span><h2>Heat-risk distribution</h2><p>Current model outputs cluster in the Orange tier for the supplied peak-day ward results.</p><div className="distribution"><DistributionBar label="Orange" value={10} total={10} cls="orange-bg"/><DistributionBar label="Yellow" value={0} total={10} cls="yellow-bg"/><DistributionBar label="Low" value={0} total={10} cls="green-bg"/></div></div><div className="panel info-panel"><span className="section-kicker">MAP READING</span><h2>How to use the map</h2><ul className="clean-list"><li>Hover a ward to inspect its identifier.</li><li>Click a modeled ward to open its metrics.</li><li>Switch between Risk, WBGT and Vulnerability.</li><li>Neutral wards indicate missing model output.</li></ul></div></div></>}
function DistributionBar({label,value,total,cls}){return <div className="dist-row"><div><span>{label}</span><b>{value}</b></div><div className="dist-track"><i className={cls} style={{width:`${(value/Math.max(total,1))*100}%`}}></i></div></div>}

function AnalyticsPage(){const bars=Object.entries(RISK).map(([id,d])=>({ward:id.replace('W',''),wbgt:d.wbgt,vuln:d.vuln*100}));return <><div className="analytics-grid"><div className="panel analytics-chart"><div className="panel-head"><div><span className="section-kicker">THERMAL HISTORY</span><h2>WBGT and UTCI</h2></div><span className="date-pill">6 DAYS</span></div><div className="chart large"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={0.12}/><XAxis dataKey="day" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip contentStyle={{borderRadius:8,border:'1px solid var(--border)',background:'var(--surface)'}}/><Area type="monotone" dataKey="wbgt" stroke="#39ff14" fill="none" strokeWidth={2.5}/><Area type="monotone" dataKey="utci" stroke="#8f9a94" fill="none" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="panel analytics-chart"><div className="panel-head"><div><span className="section-kicker">WARD COMPARISON</span><h2>WBGT by ward</h2></div></div><div className="chart large"><ResponsiveContainer width="100%" height="100%"><BarChart data={bars}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={0.1}/><XAxis dataKey="ward" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip contentStyle={{borderRadius:8,border:'1px solid var(--border)',background:'var(--surface)'}}/><Bar dataKey="wbgt" fill="#39ff14" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></div></div><section className="panel method-strip"><div><span className="section-kicker">MODEL CHECK</span><h2>Gate 4 currently fails</h2><p>Dry-bulb temperature remains the strongest feature in the consistency check. The notebook flags this for review of the health generator.</p></div><span className="warning-chip"><AlertTriangle size={14}/> REVIEW REQUIRED</span></section></>}

function AlertsPage({navigate}){return <><div className="alert-grid"><div className="alert-primary panel"><div className="alert-icon"><AlertTriangle size={21}/></div><span className="section-kicker">ACTIVE PRIORITY</span><h2>Elevated heat stress</h2><p>Peak-day model outputs place the supplied priority wards in the Orange tier.</p><button className="primary-btn" onClick={()=>navigate('Risk Map')}>Open risk map <ArrowUpRight size={15}/></button></div><div className="panel alert-list"><div className="panel-head"><div><span className="section-kicker">WARD ALERTS</span><h2>Priority queue</h2></div><span className="date-pill">10 MODELED</span></div>{Object.entries(RISK).slice(0,6).map(([id,d])=><div className="alert-row" key={id}><span className="risk-dot orange"></span><div><b>{id}</b><span>WBGT {d.wbgt.toFixed(1)}°C · UTCI {d.utci.toFixed(1)}°C</span></div><strong>ORANGE</strong></div>)}</div></div></>}

function ReportsPage(){return <div className="reports-grid"><div className="panel report-card"><FileText size={20}/><span className="section-kicker">MODEL 2</span><h2>Peak-day assessment</h2><p>Ward-level heat burden summary for 17 Jun 2023, including uncertainty bands.</p><button className="secondary-btn"><Download size={14}/> Export summary</button></div><div className="panel report-card"><ShieldCheck size={20}/><span className="section-kicker">METHODOLOGY</span><h2>Validation record</h2><p>Year-based split, heat-season coverage, leakage assertion and gate checks.</p><button className="secondary-btn">View methodology <ArrowUpRight size={14}/></button></div><div className="panel report-card"><Database size={20}/><span className="section-kicker">PROVENANCE</span><h2>Data sources</h2><p>ERA5 via Open-Meteo archive, computed thermal indices, supplied ward geometry and documented health-burden assumptions.</p><button className="secondary-btn">View provenance <ArrowUpRight size={14}/></button></div></div>}

function LayersPage({mapMode,setMapMode,navigate}){return <><div className="layer-layout"><div className="panel layer-controls"><div className="panel-head"><div><span className="section-kicker">VISIBLE LAYERS</span><h2>Map controls</h2></div><SlidersHorizontal size={17}/></div>{[['risk','Heat risk','Tiered risk classification'],['wbgt','WBGT','Outdoor thermal stress'],['vulnerability','Vulnerability','Ward vulnerability weight']].map(([id,title,desc])=><button className={mapMode===id?'layer-option active':'layer-option'} key={id} onClick={()=>setMapMode(id)}><span className="layer-swatch"></span><div><b>{title}</b><small>{desc}</small></div><span className="layer-state">{mapMode===id?'ON':'OFF'}</span></button>)}</div><div className="panel layer-note"><span className="section-kicker">DATA COVERAGE</span><h2>141 wards in geometry</h2><p>The supplied GeoJSON contains the current 141-ward geometry. Model outputs currently available in the dashboard cover 10 wards.</p><div className="coverage"><div><b>141</b><span>Mapped wards</span></div><div><b>10</b><span>Modeled wards</span></div><div><b>131</b><span>No output</span></div></div><button className="primary-btn" onClick={()=>navigate('Risk Map')}>Apply to map <ArrowUpRight size={15}/></button></div></div></>}

function SettingsPage({dark,setDark}){return <div className="settings-grid"><div className="panel settings-card"><span className="section-kicker">APPEARANCE</span><h2>Interface theme</h2><p>Switch between the command-center dark interface and a high-contrast light interface.</p><div className="theme-choice"><button className={!dark?'theme-choice active':''} onClick={()=>setDark(false)}><Sun size={17}/><span>Light</span></button><button className={dark?'theme-choice active':''} onClick={()=>setDark(true)}><Moon size={17}/><span>Dark</span></button></div></div><div className="panel settings-card"><span className="section-kicker">MODEL DISPLAY</span><h2>Forecast convention</h2><p>HEATWARD displays the burden target at the midpoint of the PS requirement.</p><div className="setting-row"><span>Forecast horizon</span><b>T + 4 DAYS</b></div><div className="setting-row"><span>Temporal split</span><b>YEAR-BASED</b></div><div className="setting-row"><span>Leakage check</span><b className="good">PASSED</b></div></div></div>}

function RiskMap({selectedWard,setSelectedWard,mapMode,tall=false}){const ref=useRef(null),mapRef=useRef(null),[loaded,setLoaded]=useState(false),[hover,setHover]=useState(null);const colors=useMemo(()=>({unknown:'#263029',low:'#39ff14',yellow:'#f2c94c',orange:'#f2994a',red:'#e05252'}),[]);
 useEffect(()=>{if(!ref.current||mapRef.current)return;const map=new maplibregl.Map({container:ref.current,style:{version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#0b110f'}}]},center:[88.36,22.57],zoom:10.3,attributionControl:false});mapRef.current=map;map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');
 map.on('load',async()=>{const geo=await fetch('/wards_kolkata.geojson').then(r=>r.json());map.addSource('wards',{type:'geojson',data:geo});
 const riskExpr=['match',['to-string',['get','WARD']]];Object.entries(RISK).forEach(([id,d])=>riskExpr.push(id.slice(1),colors.orange));riskExpr.push(colors.unknown);
 const wbgtExpr=['match',['to-string',['get','WARD']]];Object.entries(RISK).forEach(([id,d])=>wbgtExpr.push(id.slice(1),d.wbgt>=35.9?'#e05252':d.wbgt>=35.8?'#f2994a':'#f2c94c'));wbgtExpr.push(colors.unknown);
 const vulnExpr=['match',['to-string',['get','WARD']]];Object.entries(RISK).forEach(([id,d])=>vulnExpr.push(id.slice(1),d.vuln>=.7?'#39ff14':d.vuln>=.55?'#8fdc63':'#3f713f'));vulnExpr.push(colors.unknown);
 map.addLayer({id:'ward-fill',type:'fill',source:'wards',paint:{'fill-color':riskExpr,'fill-opacity':0.88}});map.addLayer({id:'ward-line',type:'line',source:'wards',paint:{'line-color':'#3b523e','line-width':0.55,'line-opacity':0.55}});map.addLayer({id:'ward-selected',type:'line',source:'wards',paint:{'line-color':'#39ff14','line-width':2.2},filter:['==',['to-string',['get','WARD']],selectedWard.replace('W','')]});
 map.fitBounds([[88.18,22.43],[88.52,22.72]],{padding:28,duration:0});setLoaded(true);
 map.on('mousemove','ward-fill',e=>{map.getCanvas().style.cursor='pointer';const f=e.features?.[0];if(f){setHover({x:e.point.x,y:e.point.y,id:String(f.properties?.WARD||'')})}});map.on('mouseleave','ward-fill',()=>{map.getCanvas().style.cursor='';setHover(null)});map.on('click','ward-fill',e=>{const id=String(e.features?.[0]?.properties?.WARD||'').trim();if(id)setSelectedWard(`W${id.padStart(2,'0')}`)});
 });return()=>map.remove();},[]);
 useEffect(()=>{const map=mapRef.current;if(!map||!loaded)return;const modeExpr=['match',['to-string',['get','WARD']]];Object.entries(RISK).forEach(([id,d])=>{const v=mapMode==='risk'?colors.orange:mapMode==='wbgt'?(d.wbgt>=35.9?'#e05252':d.wbgt>=35.8?'#f2994a':'#f2c94c'):(d.vuln>=.7?'#39ff14':d.vuln>=.55?'#8fdc63':'#3f713f');modeExpr.push(id.slice(1),v)});modeExpr.push(colors.unknown);map.setPaintProperty('ward-fill','fill-color',modeExpr);map.setFilter('ward-selected',['==',['to-string',['get','WARD']],selectedWard.replace('W','')]);},[mapMode,selectedWard,loaded,colors]);
 return <div className={tall?'map-wrap tall':'map-wrap'}><div ref={ref} className="map-canvas"></div><div className="map-legend"><b>{mapMode==='risk'?'RISK':mapMode.toUpperCase()}</b><span><i className="legend-low"></i>Lower</span><span><i className="legend-mid"></i>Elevated</span><span><i className="legend-high"></i>Higher</span><span><i className="legend-none"></i>No output</span></div>{hover&&<div className="map-tooltip" style={{left:Math.min(hover.x+14,ref.current?.clientWidth-170||hover.x+14),top:Math.max(hover.y-18,12)}}><b>WARD {hover.id.padStart(3,'0')}</b><span>{RISK[`W${hover.id.padStart(2,'0')}`]?`${RISK[`W${hover.id.padStart(2,'0')}`].tier} · ${RISK[`W${hover.id.padStart(2,'0')}`].wbgt.toFixed(1)}°C WBGT`:'No model output'}</span></div>}<div className="map-note">141 ward boundaries · no external basemap</div></div>}

createRoot(document.getElementById('root')).render(<AppErrorBoundary><App/></AppErrorBoundary>);
